2019-11-02 11:35:59,340 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', artists=artists, correct=correct)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 66, in block "content"
    alert('Correct! ' + "{{artists[" + correct + "]['name']}}" + ' is more popular than ' +
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute ' + correct + '
2019-11-02 11:36:01,845 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', artists=artists, correct=correct)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 66, in block "content"
    alert('Correct! ' + "{{artists[" + correct + "]['name']}}" + ' is more popular than ' +
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute ' + correct + '
2019-11-02 11:41:49,358 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 11:42:44,037 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 12:56:21,267 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:13:27,739 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:14:06,739 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:15:47,691 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:17:07,050 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:17:48,713 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:18:44,030 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 9, in index
    artists = spotify.get_artists()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/spotify.py", line 32, in get_artists
    artists = {'a1' : artists[0], 'a2' : artists[1]}
IndexError: list index out of range
2019-11-02 13:19:38,592 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:22:30,928 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
